---

- name: LLAMACPP-ROCM
  become: true
  tags:
    - llm
    - llamacpp
  when: llamacpp_rocm_enable
  block:

    - name: LLAMACPP-ROCM check `/opt/llamacpp-rocm/llama-server`
      ansible.builtin.command:
        cmd: /opt/llamacpp-rocm/llama-server --version
      changed_when: false
      ignore_errors: true
      register: _llamacpp_rocm_status

    - name: LLAMACPP-ROCM check `/opt/llamacpp-rocm`
      ansible.builtin.file:
        path: /opt/llamacpp-rocm
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: LLAMACPP-ROCM install llama-swap
      ansible.builtin.unarchive:
        src: "https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/{{ llamacpp_rocm_version }}/llama-{{ llamacpp_rocm_version }}-ubuntu-rocm-{{ llamacpp_rocm_variant }}-x64.zip"
        dest: /opt/llamacpp-rocm
        remote_src: true
        owner: root
        group: root
        mode: "0755"
      when: (_llamacpp_rocm_status.rc != 0) or
            (llamacpp_rocm_version not in _llamacpp_rocm_status.stdout)
